version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "112345"
    ports:
      - "5432:5432"
    volumes:
      - /Users/gustavoakashi/find-my-computer/find-my-computer/postgres/db:/var/lib/postgresql/data
